---
title: "SSA DIC"
output:
  html_document: default
  word_document: default
  pdf_document: default
date: "2023-07-01"
---

```{r library, include=FALSE}
library(readxl)
require(tidyverse)
require(rjags)
library(binom)
library(ggplot2)
library(dplyr)
library(varhandle)
require(MCMCvis)
library(cowplot)
library(viridis)
library(hrbrthemes)
library(ggridges)
library(plotly)
library(maps)
library(ggpubr)
library(tidyr)
library(ggridges)
library(gridExtra)
library(writexl)
```

## R Markdown

```{r setting, warning=FALSE}
CountryModel <- read_excel("D:/OneDrive - London School of Hygiene and Tropical Medicine/CHIK/1.Aim1/all_countries/CountryModel.xlsx", 
    sheet = "inclusion", col_types = c("numeric", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text"))
CountryModel <- read_excel("~/Library/CloudStorage/OneDrive-LondonSchoolofHygieneandTropicalMedicine/CHIK/1.Aim1/all_countries/CountryModel.xlsx", 
    sheet = "inclusion", col_types = c("text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text"))

View(CountryModel)
#Rename data
df_ssa = CountryModel %>% filter(region == "SSA")

df_ssa[,c("midpoint","lower","upper")] = binom.confint(df_ssa$N.pos, df_ssa$N, method="exact")[,c("mean","lower","upper")]

df_ssa <-  df_ssa %>% 
  dplyr::mutate(agemid = (age_min+age_max)/2)

df_ssa <- df_ssa[df_ssa$antibody != "IgM",] # remove data that has only IgM

study7       <-  df_ssa %>% filter(study_no == 7)
study7       <-  study7[1:3,]
study17      <-  df_ssa %>% filter(study_no == 17)
study106     <-  df_ssa %>% filter(study_no == 106)
study132     <-  df_ssa %>% filter(study_no == 132)
study136     <-  df_ssa %>% filter(study_no == 136)
study149     <-  df_ssa %>% filter(study_no == 149)
study170     <-  df_ssa %>% filter(study_no == 170)
study204_1   <-  df_ssa %>% filter(study_no == 204 & country == "Burkina Faso (Ouagadougou)")
study204_2   <-  df_ssa %>% filter(study_no == 204 & country == "Gabon (Lambaréné)")
study236     <-  df_ssa %>% filter(study_no == 236)
study237     <-  df_ssa %>% filter(study_no == 237)
study279     <-  df_ssa %>% filter(study_no == 279)
study306     <-  df_ssa %>% filter(study_no == 306)
study321     <-  df_ssa %>% filter(study_no == 321)
study494     <-  df_ssa %>% filter(study_no == 494)


ssa_igg <- df_ssa[df_ssa$study_no %in% c(7,17,106,149,
                                         170,204,236,237,279,306,494),]
ssa_igg <- ssa_igg[-4,]
ssa_igg[ssa_igg$study_no == 494, "country"] <- "Gabon (Lambaréné, 2014-2017)"
ssa_igg[(ssa_igg$study_no == 204) & (ssa_igg$sub_country) == "Lambaréné", "country"] <- "Gabon (Lambaréné, 2015)"

write_xlsx(ssa_igg, "D:/OneDrive - London School of Hygiene and Tropical Medicine/CHIK/1.Aim1/codes/CHIK/ssa_igg.xlsx")
```

```{r study7}
# 7
jcode <- "model{ 
	for (i in 1:3){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i] < (2007-delta),0,
                            1-exp(-lambda))
    # time-varying catalytic model
	}
	#  prior dists
  lambda ~ dunif(0,1)       #uninformative prior
  delta  ~ dunif(1988,2007) #uninformative prior
}"
paramVector <- c("lambda", "delta")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix1 <- as.matrix(jpos)

```

```{r study 17}
# 17
jcode <- "model{ 
	for (i in 5:9){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i] < (2012-delta),0,
                            1-exp(-lambda))
    # time-varying catalytic model
	}
	#  prior dists
  lambda ~ dunif(0,1)       #uninformative prior
  delta  ~ dunif(2003,2012) #uninformative prior
}"
paramVector <- c("lambda", "delta")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix2 <- as.matrix(jpos)

```

```{r study 106}
# 106
jcode <- "model{ 
	for (i in 21:24){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2016-delta4), 1-exp(-lambda1-lambda2-lambda3-lambda4),
        ifelse(age[i]> (2016-delta3) && age[i] < 45, 1-exp(-lambda1-lambda2-lambda3),
        ifelse(age[i]> (2016-delta2) && age[i] < 35, 1-exp(-lambda1-lambda2),
        ifelse(age[i]> (2016-delta1) && age[i] < 24, 1-exp(-lambda1),
        0))))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  lambda3  ~ dunif(0,1)       #uninformative prior
  lambda4  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(1993,2016)
  delta2  ~ dunif(1982,1992)
  delta3  ~ dunif(1972,1980)
  delta4  ~ dunif(1937,1970)
  
}"
paramVector <- c("lambda1","lambda2","lambda3","lambda4","delta1", "delta2", "delta3",
                    "delta4")
mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix3 <- as.matrix(jpos)

```

```{r study 149}
# 149
jcode <- "model{ 
	for (i in 43:47){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2018-delta2), 1-exp(-lambda1-lambda2)
       ,ifelse(age[i]> (2018-delta1) && age[i] < 10, 1-exp(-lambda1),
       0))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(2009,2018)
  delta2  ~ dunif(1999,2007)
}"
paramVector <- c("lambda1","lambda2", "delta1", "delta2")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix4 <- as.matrix(jpos)

```

```{r study 170}
jcode <- "model{ 
	for (i in 48:50){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = 1-exp(-lambda*age[i]) #catalytic model
	}
		#  prior dists
  lambda ~ dunif(0,1) #uninformative prior
}"
paramVector <- c("lambda")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix5 <- as.matrix(jpos)

```

```{r study 204_1}
jcode <- "model{ 
	for (i in 55:65){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2015-delta5), 1-exp(-lambda5*age[i]),
        ifelse(age[i]> (2015-delta4) && age[i] < 19, 1-exp(-lambda1-lambda2-lambda3-lambda4),
        ifelse(age[i]> (2015-delta3) && age[i] < 14, 1-exp(-lambda1-lambda2-lambda3),
        ifelse(age[i]> (2015-delta2) && age[i] < 9, 1-exp(-lambda1-lambda2),
        ifelse(age[i]> (2015-delta1) && age[i] < 4, 1-exp(-lambda1),
        0)))))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  lambda3  ~ dunif(0,1)       #uninformative prior
  lambda4  ~ dunif(0,1)       #uninformative prior
  lambda5  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(2012,2015)
  delta2  ~ dunif(2007,2010)
  delta3  ~ dunif(2002,2005)
  delta4  ~ dunif(1997,2000)
  delta5  ~ dunif(1992,1995)
}"
paramVector <- c("lambda1","lambda2","lambda3","lambda4","lambda5","delta1", "delta2", "delta3",
                 "delta4","delta5")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix6 <- as.matrix(jpos)

```

```{r study 204_2}
jcode <- "model{ 
	for (i in 66:76){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2015-delta2), 1-exp(-lambda1-lambda2)
       ,ifelse(age[i]> (2015-delta1) && age[i] < 4, 1-exp(-lambda1),
       0))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(2012,2015)
  delta2  ~ dunif(2007,2010)
}"
paramVector <- c("lambda1","lambda2", "delta1", "delta2")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix7 <- as.matrix(jpos)

```

```{r study 236}
# 236
jcode <- "model{ 
	for (i in 84:89){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i] < (2005-delta),0,
                            1-exp(-lambda))
    # time-varying catalytic model
	}
	#  prior dists
  lambda ~ dunif(0,1)       #uninformative prior
  delta  ~ dunif(1992,2005) #uninformative prior
}"
paramVector <- c("lambda", "delta")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix8 <- as.matrix(jpos)

```

```{r study 237}
jcode <- "model{ 
	for (i in 90:94){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2004-delta4), 1-exp(-lambda1-lambda2-lambda3-lambda4),
        ifelse(age[i]> (2004-delta3) && age[i] < 24, 1-exp(-lambda1-lambda2-lambda3),
        ifelse(age[i]> (2004-delta2) && age[i] < 14, 1-exp(-lambda1-lambda2),
        ifelse(age[i]> (2004-delta1) && age[i] < 4, 1-exp(-lambda1),
        0))))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  lambda3  ~ dunif(0,1)       #uninformative prior
  lambda4  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(2001,2004)
  delta2  ~ dunif(1991,1999)
  delta3  ~ dunif(1981,1989)
  delta4  ~ dunif(1956,1979)
}"
paramVector <- c("lambda1","lambda2","lambda3","lambda4","delta1", "delta2", "delta3",
                 "delta4")
mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix9 <- as.matrix(jpos)

```

```{r study 279}
jcode <- "model{ 
	for (i in 95:99){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2007-delta4), 1-exp(-lambda1-lambda2-lambda3-lambda4),
        ifelse(age[i]> (2007-delta3) && age[i] < 44, 1-exp(-lambda1-lambda2-lambda3),
        ifelse(age[i]> (2007-delta2) && age[i] < 29, 1-exp(-lambda1-lambda2),
        ifelse(age[i]> (2007-delta1) && age[i] < 14, 1-exp(-lambda1),
        0))))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  lambda3  ~ dunif(0,1)       #uninformative prior
  lambda4  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(1994,2007)
  delta2  ~ dunif(1979,1992)
  delta3  ~ dunif(1964,1977)
  delta4  ~ dunif(1949,1962)
}"
paramVector <- c("lambda1","lambda2","lambda3","lambda4","delta1", "delta2", "delta3",
                    "delta4")
mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix10 <- as.matrix(jpos)

```

```{r study 306}
jcode <- "model{ 
	for (i in 105:111){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = 1-exp(-lambda*age[i]) #catalytic model
	}
		#  prior dists
  lambda ~ dunif(0,1) #uninformative prior
}"
paramVector <- c("lambda")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix11 <- as.matrix(jpos)

```

```{r study 494}
jcode <- "model{ 
	for (i in 141:144){
    n.pos[i] ~ dbinom(seropos_est[i],N[i]) #fit to binomial data
    seropos_est[i] = ifelse(age[i]> (2017-delta3), 1-exp(-lambda1-lambda2-lambda3),
        ifelse(age[i]> (2017-delta2) && age[i] < 11, 1-exp(-lambda1-lambda2),
        ifelse(age[i]> (2017-delta1) && age[i] < 2, 1-exp(-lambda1),
       0)))
    # time-varying catalytic model
	}
	#  prior dists
  lambda1  ~ dunif(0,1)       #uninformative prior
  lambda2  ~ dunif(0,1)       #uninformative prior
  lambda3  ~ dunif(0,1)       #uninformative prior
  delta1  ~ dunif(2016,2017)
  delta2  ~ dunif(2007,2014)
  delta3  ~ dunif(2001,2005)
  
}"
paramVector <- c("lambda1","lambda2","lambda3", "delta1", "delta2", "delta3")

mcmc.length=50000
jdat = list(n.pos= df_ssa$N.pos,
            N=df_ssa$N,
            age=df_ssa$agemid)
jmod = jags.model(textConnection(jcode), data=jdat, n.chains=4, n.adapt = 15000)
update(jmod, 500)
jpos = coda.samples(jmod, paramVector, n.iter=mcmc.length)

summary(jpos) 
mcmcMatrix12 <- as.matrix(jpos)

```

```{r Function}
# credible interval
constantCR <- function(paramVector, mcmcMatrix) {
  
  ager = 0:80
  numSamples = 1000
  
  for(ii in 1:length(paramVector)) {
  
  outDf <- matrix(NA, nrow=numSamples, ncol=length(ager))
  
  for (kk in 1:numSamples ) {
    randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
    
    lambdaSample <- mcmcMatrix[sample(nrow(mcmcMatrix), 1, replace=T), "lambda"]

    newRow  <-  1-exp(-lambdaSample*ager)

    outDf[kk,] <- newRow
  }
}
  return(outDf)
}

Epi1CR <- function(paramVector, mcmcMatrix, ager1, ager2){
  
  numSamples = 1000
  
  for(ii in 1:length(paramVector)) {
    
    outDf_1 <- matrix(NA,nrow=numSamples, ncol = length(ager1))
    outDf_2 <- matrix(NA,nrow=numSamples, ncol = length(ager2))
    
    
    for (kk in 1:numSamples ) {
      randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
      
      lambdaSample <- mcmcMatrix[randomNumber,"lambda"]
      deltaSample  <- mcmcMatrix[randomNumber,"delta"]
      
      newRow_1 <- 0
      newRow_2 <- 1-exp(-lambdaSample)
      
      outDf_1[kk,] <- newRow_1
      outDf_2[kk,] <- newRow_2
      
      outDf <- cbind(outDf_1,outDf_2)
    }
  }
  return(outDf)
}

Epi2CR <- function(paramVector, mcmcMatrix, ager1, ager2, ager3){
  numSamples = 1000
  for(ii in 1:length(paramVector)) {
    
    outDf_1 <- matrix(NA,nrow=numSamples, ncol = length(ager1))
    outDf_2 <- matrix(NA,nrow=numSamples, ncol = length(ager2))
    outDf_3 <- matrix(NA,nrow=numSamples, ncol = length(ager3))
    
    for (kk in 1:numSamples ) {
      randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
      
      lambdaSample1   <- mcmcMatrix[randomNumber,"lambda1"]
      lambdaSample2   <- mcmcMatrix[randomNumber,"lambda2"]
      deltaSample_1   <- mcmcMatrix[randomNumber,"delta1"]
      deltaSample_2   <- mcmcMatrix[randomNumber,"delta2"]
      
      newRow_1 <- 0
      newRow_2 <- 1-exp(-lambdaSample1)
      newRow_3 <- 1-exp(-lambdaSample1-lambdaSample2)
      
      outDf_1[kk,] <- newRow_1
      outDf_2[kk,] <- newRow_2
      outDf_3[kk,] <- newRow_3
      
      outDf <- cbind(outDf_1,outDf_2,outDf_3)
    }
  }
  return(outDf)
}

Epi3CR <- function(paramVector, mcmcMatrix, ager1, ager2, ager3, ager4){
  numSamples = 1000
  for(ii in 1:length(paramVector)) {
    
    outDf_1 <- matrix(NA,nrow=numSamples, ncol = length(ager1))
    outDf_2 <- matrix(NA,nrow=numSamples, ncol = length(ager2))
    outDf_3 <- matrix(NA,nrow=numSamples, ncol = length(ager3))
    outDf_4 <- matrix(NA,nrow=numSamples, ncol = length(ager4))
    
    for (kk in 1:numSamples ) {
      randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
      
      lambdaSample1    <- mcmcMatrix[randomNumber,"lambda1"]
      lambdaSample2    <- mcmcMatrix[randomNumber,"lambda2"]
      lambdaSample3    <- mcmcMatrix[randomNumber,"lambda3"]
      
      deltaSample_1   <- mcmcMatrix[randomNumber,"delta1"]
      deltaSample_2   <- mcmcMatrix[randomNumber,"delta2"]
      deltaSample_3   <- mcmcMatrix[randomNumber,"delta3"]
      
      newRow_1 <- 0
      newRow_2 <- 1-exp(-lambdaSample1)
      newRow_3 <- 1-exp(-lambdaSample1-lambdaSample2)
      newRow_4 <- 1-exp(-lambdaSample1-lambdaSample2-lambdaSample3)
      
      outDf_1[kk,] <- newRow_1
      outDf_2[kk,] <- newRow_2
      outDf_3[kk,] <- newRow_3
      outDf_4[kk,] <- newRow_4
      
      outDf <- cbind(outDf_1,outDf_2,outDf_3,outDf_4)
    }
  }
  return(outDf)
}

Epi4CR <- function(paramVector, mcmcMatrix, ager1, ager2, ager3, ager4, ager5){
  numSamples = 1000
  for(ii in 1:length(paramVector)) {
    
    outDf_1 <- matrix(NA,nrow=numSamples, ncol = length(ager1))
    outDf_2 <- matrix(NA,nrow=numSamples, ncol = length(ager2))
    outDf_3 <- matrix(NA,nrow=numSamples, ncol = length(ager3))
    outDf_4 <- matrix(NA,nrow=numSamples, ncol = length(ager4))
    outDf_5 <- matrix(NA,nrow=numSamples, ncol = length(ager5))
    
    for (kk in 1:numSamples ) {
      randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
      
      lambdaSample1    <- mcmcMatrix[randomNumber,"lambda1"]
      lambdaSample2    <- mcmcMatrix[randomNumber,"lambda2"]
      lambdaSample3    <- mcmcMatrix[randomNumber,"lambda3"]
      lambdaSample4    <- mcmcMatrix[randomNumber,"lambda4"]
      
      deltaSample_1   <- mcmcMatrix[randomNumber,"delta1"]
      deltaSample_2   <- mcmcMatrix[randomNumber,"delta2"]
      deltaSample_3   <- mcmcMatrix[randomNumber,"delta3"]
      deltaSample_4   <- mcmcMatrix[randomNumber,"delta4"]
      
      newRow_1 <- 0
      newRow_2 <- 1-exp(-lambdaSample1)
      newRow_3 <- 1-exp(-(lambdaSample1+lambdaSample2))
      newRow_4 <- 1-exp(-(lambdaSample1+lambdaSample2+lambdaSample3))
      newRow_5 <- 1-exp(-(lambdaSample1+lambdaSample2+lambdaSample3+lambdaSample4))
      
      outDf_1[kk,] <- newRow_1
      outDf_2[kk,] <- newRow_2
      outDf_3[kk,] <- newRow_3
      outDf_4[kk,] <- newRow_4
      outDf_5[kk,] <- newRow_5
      
      outDf <- cbind(outDf_1,outDf_2,outDf_3,outDf_4,outDf_5)
    }
  }
  return(outDf)
}

Epi5Con <- function(paramVector, mcmcMatrix, ager1, ager2, ager3, ager4, ager5,ager6){
  numSamples = 1000
  for(ii in 1:length(paramVector)) {
    
    outDf_1 <- matrix(NA,nrow=numSamples, ncol = length(ager1))
    outDf_2 <- matrix(NA,nrow=numSamples, ncol = length(ager2))
    outDf_3 <- matrix(NA,nrow=numSamples, ncol = length(ager3))
    outDf_4 <- matrix(NA,nrow=numSamples, ncol = length(ager4))
    outDf_5 <- matrix(NA,nrow=numSamples, ncol = length(ager5))
    outDf_6 <- matrix(NA,nrow=numSamples, ncol = length(ager6))
    
    for (kk in 1:numSamples ) {
      randomNumber <- floor(runif(1, min = 1, max = nrow(mcmcMatrix)))
      
      lambdaSample1    <- mcmcMatrix[randomNumber,"lambda1"]
      lambdaSample2    <- mcmcMatrix[randomNumber,"lambda2"]
      lambdaSample3    <- mcmcMatrix[randomNumber,"lambda3"]
      lambdaSample4    <- mcmcMatrix[randomNumber,"lambda4"]
      lambdaSample5    <- mcmcMatrix[randomNumber,"lambda5"]
      
      deltaSample_1   <- mcmcMatrix[randomNumber,"delta1"]
      deltaSample_2   <- mcmcMatrix[randomNumber,"delta2"]
      deltaSample_3   <- mcmcMatrix[randomNumber,"delta3"]
      deltaSample_4   <- mcmcMatrix[randomNumber,"delta4"]
      deltaSample_5   <- mcmcMatrix[randomNumber,"delta5"]
      
      newRow_1 <- 0
      newRow_2 <- 1-exp(-lambdaSample1)
      newRow_3 <- 1-exp(-(lambdaSample1+lambdaSample2))
      newRow_4 <- 1-exp(-(lambdaSample1+lambdaSample2+lambdaSample3))
      newRow_5 <- 1-exp(-(lambdaSample1+lambdaSample2+lambdaSample3+lambdaSample4))
      newRow_5 <- 1-exp(-(lambdaSample1+lambdaSample2+lambdaSample3+lambdaSample4))
      newRow_6 <- 1-exp(-lambdaSample5*ager6)
      
      outDf_1[kk,] <- newRow_1
      outDf_2[kk,] <- newRow_2
      outDf_3[kk,] <- newRow_3
      outDf_4[kk,] <- newRow_4
      outDf_5[kk,] <- newRow_5
      outDf_6[kk,] <- newRow_6
      
      outDf <- cbind(outDf_1,outDf_2,outDf_3,outDf_4,outDf_5,outDf_6)
    }
  }
  return(outDf)
  
}

# get quantile matrices function
quantmat <- function(outDf){
  ager = 0:80
  quantileMatrix <- matrix(NA,nrow=ncol(outDf), ncol = 3)
  for(jj in 1:ncol(outDf)){
    quantiles <- outDf[,jj] %>% quantile(probs=c(.5,.025,.975))
    quantileMatrix[jj,] <- quantiles
  }
  df_upperLower <- cbind(ager, quantileMatrix)
  df_upperLower <- as.data.frame(df_upperLower)
  colnames(df_upperLower) <- c('agemid', 'mean', 'upper', 'lower')
  return(df_upperLower)
}
plotfuncXY <- function(df_upperLower, study){
  g <- ggplot()+
    geom_line(data = df_upperLower, aes(x=agemid, y=mean), color = "#558C8C")+
    geom_ribbon(data = df_upperLower, alpha=0.2, aes(x=agemid, y=mean, ymin=lower, ymax=upper), fill = "#558C8C")+
    geom_point(data = study, aes(x=agemid, y=midpoint), color = "#558C8C")+  
    geom_linerange(data = study, aes(x=agemid, ymin=lower, ymax=upper), color = "#558C8C")+
    theme_bw()+
    theme(axis.line.x = element_blank(),
          axis.title.x = element_blank())+
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    ylim(0, 1)+
    xlab(element_blank()) + 
    ylab(element_blank())+
    scale_fill_viridis(discrete = T)+
    facet_wrap(~ country, nrow = 1) 
  return(g)
}

plotfuncNone <- function(df_upperLower, study){
  g <- ggplot()+
    geom_line(data = df_upperLower, aes(x=agemid, y=mean), color = "#558C8C")+
    geom_ribbon(data = df_upperLower, alpha=0.2, aes(x=agemid, y=mean, ymin=lower, ymax=upper), fill = "#558C8C")+
    geom_point(data = study, aes(x=agemid, y=midpoint), color = "#558C8C")+  
    geom_linerange(data = study, aes(x=agemid, ymin=lower, ymax=upper), color = "#558C8C")+
    theme_bw()+
    theme(axis.line.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_blank())+
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    ylim(0, 1)+
    xlab(element_blank()) + 
    ylab(element_blank())+
    scale_fill_viridis(discrete = T)+
    facet_wrap(~ country, nrow = 1) 
  return(g)
}

#ggplot function 1) y axis only 
plotfuncYonly <- function(df_upperLower, study){
  g <- ggplot()+
    geom_line(data = df_upperLower, aes(x=agemid, y=mean), color = "#558C8C")+
    geom_ribbon(data = df_upperLower, alpha=0.2, aes(x=agemid, y=mean, ymin=lower, ymax=upper), fill = "#558C8C")+
    geom_point(data = study, aes(x=agemid, y=midpoint), color = "#558C8C")+  
    geom_linerange(data = study, aes(x=agemid, ymin=lower, ymax=upper), color = "#558C8C")+
    theme_bw()+
    theme(axis.line.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank())+
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    ylim(0, 1)+
    xlab(element_blank()) + 
    ylab(element_blank())+
    scale_fill_viridis(discrete = T)+
    facet_wrap(~ country, nrow = 1) 
  return(g)
}
#ggplot function 1) x axis only 
plotfuncXonly <- function(df_upperLower, study){
  g <- ggplot()+
    geom_line(data = df_upperLower, aes(x=agemid, y=mean), color = "#558C8C")+
    geom_ribbon(data = df_upperLower, alpha=0.2, aes(x=agemid, y=mean, ymin=lower, ymax=upper), fill = "#558C8C")+
    geom_point(data = study, aes(x=agemid, y=midpoint), color = "#558C8C")+  
    geom_linerange(data = study, aes(x=agemid, ymin=lower, ymax=upper), color = "#558C8C")+
    theme_bw()+
    theme(axis.line.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_blank())+
    scale_x_continuous(breaks = seq(0, 100, by = 10)) +
    ylim(0, 1)+
    xlab(element_blank()) + 
    ylab(element_blank())+
    scale_fill_viridis(discrete = T)+
    facet_wrap(~ country, nrow = 1) +
    theme(strip.text = element_text(size = 8))
  return(g)
}


```

```{r Result: study7}
outDf7 <-Epi1CR(paramVector, mcmcMatrix1, ager1=0:8, ager2=9:80) 
df_upperLower7 <- quantmat(outDf7)
g3<-plot7 <- plotfuncYonly(df_upperLower7, study7)

outDf17 <-Epi1CR(paramVector, mcmcMatrix2, ager1=0:3, ager2=4:80) 
df_upperLower17 <- quantmat(outDf17)
g4<-plot17 <- plotfuncXY(df_upperLower17, study17)

outDf106 <- Epi4CR(paramVector, mcmcMatrix3, ager1 = 0:10, ager2= 11:26, ager3= 27:38, ager4=39:54, ager5=55:80)
df_upperLower106 <- quantmat(outDf106)
g9<-plot106 <- plotfuncXonly(df_upperLower106, study106)

outDf149 <- Epi2CR(paramVector, mcmcMatrix4, ager1=0:3, ager2=4:13, ager3=14:80)
df_upperLower149 <- quantmat(outDf149)
g6<-plot149 <- plotfuncNone(df_upperLower149, study149)

outDf170 <- constantCR(paramVector, mcmcMatrix5)
df_upperLower170 <- quantmat(outDf170)
g1<- plot170 <- plotfuncNone(df_upperLower170, study170)

outDf204_1 <- Epi5Con(paramVector, mcmcMatrix6, ager1 = 0:0, ager2=1:5, ager3=6:10, ager4=11:15, ager5=16:20, ager6=21:80)
df_upperLower204_1 <- quantmat(outDf204_1)
g12<-plot204_1 <- plotfuncNone(df_upperLower204_1, study204_1)

outDf204_2 <- Epi2CR(paramVector, mcmcMatrix7, ager1=0:1, ager2=2:5, ager3=6:80)
df_upperLower204_2 <- quantmat(outDf204_2)
g7<-plot204_2 <- plotfuncYonly(df_upperLower204_2, study204_2)

outDf236 <-Epi1CR(paramVector, mcmcMatrix8, ager1=0:2, ager2=3:80) 
df_upperLower236 <- quantmat(outDf236)
g5<-plot236 <- plotfuncYonly(df_upperLower236, study236)

outDf237 <- Epi4CR(paramVector, mcmcMatrix9, ager1 = 0:1, ager2=2:7, ager3=8:17, ager4=18:31, ager5=32:80)
df_upperLower237 <- quantmat(outDf237)
g10<-plot237 <- plotfuncNone(df_upperLower237, study237)

outDf279 <- Epi4CR(paramVector, mcmcMatrix10, ager1 = 0:4, ager2=5:18, ager3=19:33, ager4=34:48, ager5=49:80)
df_upperLower279 <- quantmat(outDf279)
g11<-plot279 <- plotfuncNone(df_upperLower279, study279)

outDf306 <- constantCR(paramVector, mcmcMatrix11)
df_upperLower306 <- quantmat(outDf306)
g2 <-plot306 <- plotfuncXonly(df_upperLower306, study306)

outDf494 <- Epi3CR(paramVector, mcmcMatrix12, ager1 = 0:0, ager2= 1:3, ager3= 4:13, ager4=14:80)
df_upperLower494 <- quantmat(outDf494)
g8<-plot494 <- plotfuncNone(df_upperLower494, study494)
```

## Final graph
```{r Plot, echo= FALSE}
          grid.arrange(g1, g2, g3, g4,
                          g5, g6, g7, g8,
                          g9, g10, g11,g12, ncol=3,
                          left = "Proportion Seropositive",
                          bottom = "Age (years)",
                          top = "Seropositivity in SSA (non-fever population based studies)")

ssa_sero <-   grid.arrange(g3, g12, g11, g5,
                          g6, g1, g7, g8,
                          g10, g4, g2,g9, ncol=3)
ggsave("ssa_sero.pdf", ssa_sero, dpi=1000, device= "pdf", height=8, width=10,units="in", bg=NULL)

# sample graphs (for presentation)
g1  <- plotfuncYonly(df_upperLower170, study170)
g2 <- plotfuncNone(df_upperLower306, study306)
g11  <- plotfuncXY(df_upperLower279, study279)
g9 <- plotfuncXonly(df_upperLower106, study106)
ssa_vimc <- grid.arrange(g1,g2,g11,g9, ncol = 2,
                         left = "Seroprevalence",
                         bottom = "Age")
ggsave("ssa_vimc.pdf", ssa_vimc, dpi=1000, device= "pdf", height=5, width=7,units="in", bg=NULL)

```

```{r FOI matrix}
#study 7 
mcmcMatrix1 <- as.data.frame(mcmcMatrix1)
foimat1 <- as.data.frame(matrix(NA, nrow = 4, ncol = 4))
colnames(foimat1) <- c("Year", "FOI", "lo", "hi")
foimat1[,1] <- c(1965, 1998, 1998, 2007)
foimat1[1:2,2] <- quantile(mcmcMatrix1$lambda, c(0.5))
foimat1[1:2,3] <- quantile(mcmcMatrix1$lambda, c(0.025))
foimat1[1:2,4] <- quantile(mcmcMatrix1$lambda, c(0.975))
foimat1[3:4,2:4] <- 0
foimat1$country <- c("Benin (Cotonou)")

#study 204_1
mcmcMatrix6 <- as.data.frame(mcmcMatrix6)
foimat2 <- as.data.frame(matrix(NA, nrow = 12, ncol = 4))
colnames(foimat2) <- c("Year", "FOI", "lo", "hi")
foimat2[,1] <- c(1960, 1993, 1993, 1999 ,1999 ,2004 ,2004, 2008 ,2008, 2013, 2013, 2015)
foimat2[1:2,2] <- quantile(mcmcMatrix6$lambda1, c(0.5))
foimat2[1:2,3] <- quantile(mcmcMatrix6$lambda1, c(0.025))
foimat2[1:2,4] <- quantile(mcmcMatrix6$lambda1, c(0.975))

foimat2[3:4,2] <- quantile(mcmcMatrix6$lambda2, c(0.5))
foimat2[3:4,3] <- quantile(mcmcMatrix6$lambda2, c(0.025))
foimat2[3:4,4] <- quantile(mcmcMatrix6$lambda2, c(0.975))

foimat2[5:6,2] <- quantile(mcmcMatrix6$lambda3, c(0.5))
foimat2[5:6,3] <- quantile(mcmcMatrix6$lambda3, c(0.025))
foimat2[5:6,4] <- quantile(mcmcMatrix6$lambda3, c(0.975))

foimat2[7:8,2] <- quantile(mcmcMatrix6$lambda4, c(0.5))
foimat2[7:8,3] <- quantile(mcmcMatrix6$lambda4, c(0.025))
foimat2[7:8,4] <- quantile(mcmcMatrix6$lambda4, c(0.975))

foimat2[9:10,2] <- quantile(mcmcMatrix6$lambda5, c(0.5))
foimat2[9:10,3] <- quantile(mcmcMatrix6$lambda5, c(0.025))
foimat2[9:10,4] <- quantile(mcmcMatrix6$lambda5, c(0.975))

foimat2[11:12,2:4] <- 0
foimat2$country <- c("Burkina Faso (Ouagadougou)")

#study 279
mcmcMatrix10 <- as.data.frame(mcmcMatrix10)
foimat3 <- as.data.frame(matrix(NA, nrow = 10, ncol = 4))
colnames(foimat3) <- c("Year", "FOI", "lo", "hi")
foimat3[,1] <- c(1927, 1958, 1958, 1973, 1973, 1988, 1988, 2002, 2002, 2007)

foimat3[1:2,2] <- quantile(mcmcMatrix10$lambda1, c(0.5))
foimat3[1:2,3] <- quantile(mcmcMatrix10$lambda1, c(0.025))
foimat3[1:2,4] <- quantile(mcmcMatrix10$lambda1, c(0.975))

foimat3[3:4,2] <- quantile(mcmcMatrix10$lambda2, c(0.5))
foimat3[3:4,3] <- quantile(mcmcMatrix10$lambda2, c(0.025))
foimat3[3:4,4] <- quantile(mcmcMatrix10$lambda2, c(0.975))

foimat3[5:6,2] <- quantile(mcmcMatrix10$lambda3, c(0.5))
foimat3[5:6,3] <- quantile(mcmcMatrix10$lambda3, c(0.025))
foimat3[5:6,4] <- quantile(mcmcMatrix10$lambda3, c(0.975))

foimat3[7:8,2] <- quantile(mcmcMatrix10$lambda4, c(0.5))
foimat3[7:8,3] <- quantile(mcmcMatrix10$lambda4, c(0.025))
foimat3[7:8,4] <- quantile(mcmcMatrix10$lambda4, c(0.975))

foimat3[9:10,2:4] <- 0
foimat3$country <- c("Cameroon (Kumbo)")

#study236
mcmcMatrix8 <- as.data.frame(mcmcMatrix8)
foimat4 <- as.data.frame(matrix(NA, nrow = 4, ncol = 4))
colnames(foimat4) <- c("Year", "FOI", "lo", "hi")
foimat4[,1] <- c(1925, 2000, 2000, 2005)
foimat4[1:2,2] <- quantile(mcmcMatrix8$lambda, c(0.5))
foimat4[1:2,3] <- quantile(mcmcMatrix8$lambda, c(0.025))
foimat4[1:2,4] <- quantile(mcmcMatrix8$lambda, c(0.975))
foimat4[3:4,2:4] <- 0
foimat4$country <- c("Comoros")

#study149
mcmcMatrix4 <- as.data.frame(mcmcMatrix4)
foimat5 <- as.data.frame(matrix(NA, nrow = 6, ncol = 4))
colnames(foimat5) <- c("Year", "FOI", "lo", "hi")
foimat5[,1] <- c(1938, 2004, 2004, 2014, 2014, 2018)
foimat5[1:2,2] <- quantile(mcmcMatrix4$lambda2, c(0.5))
foimat5[1:2,3] <- quantile(mcmcMatrix4$lambda2, c(0.025))
foimat5[1:2,4] <- quantile(mcmcMatrix4$lambda2, c(0.975))

foimat5[3:4,2] <- quantile(mcmcMatrix4$lambda1, c(0.5))
foimat5[3:4,3] <- quantile(mcmcMatrix4$lambda1, c(0.025))
foimat5[3:4,4] <- quantile(mcmcMatrix4$lambda1, c(0.975))
foimat5[5:6,2:4] <- 0
foimat5$country <- c("Ethiopia (South Omo)")

#study 170
mcmcMatrix5 <- as.data.frame(mcmcMatrix5)
foimat6 <- as.data.frame(matrix(NA, nrow = 2, ncol = 4))
colnames(foimat6) <- c("Year", "FOI", "lo", "hi")
foimat6[,1] <- c(1939, 2019)
foimat6[1:2,2] <- quantile(mcmcMatrix5$lambda, c(0.5))
foimat6[1:2,3] <- quantile(mcmcMatrix5$lambda, c(0.025))
foimat6[1:2,4] <- quantile(mcmcMatrix5$lambda, c(0.975))
foimat6$country <- c("Ethiopia (Gambella)")

#study204_2
mcmcMatrix7 <- as.data.frame(mcmcMatrix7)
foimat7 <- as.data.frame(matrix(NA, nrow = 6, ncol = 4))
colnames(foimat7) <- c("Year", "FOI", "lo", "hi")
foimat7[,1] <- c(1960, 2009, 2009, 2013, 2013, 2015)
foimat7[1:2,2] <- quantile(mcmcMatrix7$lambda2, c(0.5))
foimat7[1:2,3] <- quantile(mcmcMatrix7$lambda2, c(0.025))
foimat7[1:2,4] <- quantile(mcmcMatrix7$lambda2, c(0.975))

foimat7[3:4,2] <- quantile(mcmcMatrix7$lambda1, c(0.5))
foimat7[3:4,3] <- quantile(mcmcMatrix7$lambda1, c(0.025))
foimat7[3:4,4] <- quantile(mcmcMatrix7$lambda1, c(0.975))
foimat7[5:6,2:4] <- 0
foimat7$country <- c("Gabon (Lambaréné)")

#study 494
mcmcMatrix12 <- as.data.frame(mcmcMatrix12)
foimat8 <- as.data.frame(matrix(NA, nrow = 8, ncol = 4))
colnames(foimat8) <- c("Year", "FOI", "lo", "hi")
foimat8[,1] <- c(1917, 2003, 2003, 2012, 2012, 2016, 2016, 2017)

foimat8[1:2,2] <- quantile(mcmcMatrix12$lambda3, c(0.5))
foimat8[1:2,3] <- quantile(mcmcMatrix12$lambda3, c(0.025))
foimat8[1:2,4] <- quantile(mcmcMatrix12$lambda3, c(0.975))

foimat8[3:4,2] <- quantile(mcmcMatrix12$lambda2, c(0.5))
foimat8[3:4,3] <- quantile(mcmcMatrix12$lambda2, c(0.025))
foimat8[3:4,4] <- quantile(mcmcMatrix12$lambda2, c(0.975))

foimat8[5:6,2] <- quantile(mcmcMatrix12$lambda1, c(0.5))
foimat8[5:6,3] <- quantile(mcmcMatrix12$lambda1, c(0.025))
foimat8[5:6,4] <- quantile(mcmcMatrix12$lambda1, c(0.975))
foimat8[7:8,2:4] <- 0
foimat8$country <- c("Gabon (Lambaréné)")

#study 237
mcmcMatrix9 <- as.data.frame(mcmcMatrix9)
foimat9 <- as.data.frame(matrix(NA, nrow = 10, ncol = 4))
colnames(foimat9) <- c("Year", "FOI", "lo", "hi")
foimat9[,1] <- c(1904, 1970, 1970, 1985, 1985, 1995, 1995, 2002, 2002, 2004)

foimat9[1:2,2] <- quantile(mcmcMatrix9$lambda4, c(0.5))
foimat9[1:2,3] <- quantile(mcmcMatrix9$lambda4, c(0.025))
foimat9[1:2,4] <- quantile(mcmcMatrix9$lambda4, c(0.975))

foimat9[3:4,2] <- quantile(mcmcMatrix9$lambda3, c(0.5))
foimat9[3:4,3] <- quantile(mcmcMatrix9$lambda3, c(0.025))
foimat9[3:4,4] <- quantile(mcmcMatrix9$lambda3, c(0.975))

foimat9[5:6,2] <- quantile(mcmcMatrix9$lambda2, c(0.5))
foimat9[5:6,3] <- quantile(mcmcMatrix9$lambda2, c(0.025))
foimat9[5:6,4] <- quantile(mcmcMatrix9$lambda2, c(0.975))

foimat9[7:8,2] <- quantile(mcmcMatrix9$lambda1, c(0.5))
foimat9[7:8,3] <- quantile(mcmcMatrix9$lambda1, c(0.025))
foimat9[7:8,4] <- quantile(mcmcMatrix9$lambda1, c(0.975))
foimat9[9:10,2:4] <- 0
foimat9$country <- c("Kenya (Lamu Island)")

#study17
mcmcMatrix2 <- as.data.frame(mcmcMatrix2)
foimat10 <- as.data.frame(matrix(NA, nrow = 4, ncol = 4))
colnames(foimat10) <- c("Year", "FOI", "lo", "hi")
foimat10[,1] <- c(1932, 2008, 2008, 2012)
foimat10[1:2,2] <- quantile(mcmcMatrix2$lambda, c(0.5))
foimat10[1:2,3] <- quantile(mcmcMatrix2$lambda, c(0.025))
foimat10[1:2,4] <- quantile(mcmcMatrix2$lambda, c(0.975))
foimat10[3:4,2:4] <- 0
foimat10$country <- c("Senegal (Kedougou)")

#study306
mcmcMatrix11 <- as.data.frame(mcmcMatrix11)
foimat11 <- as.data.frame(matrix(NA, nrow = 2, ncol = 4))
colnames(foimat11) <- c("Year", "FOI", "lo", "hi")
foimat11[,1] <- c(1933, 2014)
foimat11[1:2,2] <- quantile(mcmcMatrix11$lambda, c(0.5))
foimat11[1:2,3] <- quantile(mcmcMatrix11$lambda, c(0.025))
foimat11[1:2,4] <- quantile(mcmcMatrix11$lambda, c(0.975))
foimat11$country <- c("Senegal (Dagana/Podor/Pété/Ranérou/Kanel)")

#study 106
mcmcMatrix3 <- as.data.frame(mcmcMatrix3)
foimat12 <- as.data.frame(matrix(NA, nrow = 10, ncol = 4))
colnames(foimat12) <- c("Year", "FOI", "lo", "hi")
foimat12[,1] <- c(1936, 1957, 1957, 1976, 1976, 1987, 1987, 2000, 2000, 2016)

foimat12[1:2,2] <- quantile(mcmcMatrix3$lambda4, c(0.5))
foimat12[1:2,3] <- quantile(mcmcMatrix3$lambda4, c(0.025))
foimat12[1:2,4] <- quantile(mcmcMatrix3$lambda4, c(0.975))

foimat12[3:4,2] <- quantile(mcmcMatrix3$lambda3, c(0.5))
foimat12[3:4,3] <- quantile(mcmcMatrix3$lambda3, c(0.025))
foimat12[3:4,4] <- quantile(mcmcMatrix3$lambda3, c(0.975))

foimat12[5:6,2] <- quantile(mcmcMatrix3$lambda2, c(0.5))
foimat12[5:6,3] <- quantile(mcmcMatrix3$lambda2, c(0.025))
foimat12[5:6,4] <- quantile(mcmcMatrix3$lambda2, c(0.975))

foimat12[7:8,2] <- quantile(mcmcMatrix3$lambda1, c(0.5))
foimat12[7:8,3] <- quantile(mcmcMatrix3$lambda1, c(0.025))
foimat12[7:8,4] <- quantile(mcmcMatrix3$lambda1, c(0.975))
foimat12[9:10,2:4] <- 0
foimat12$country <- c("Zambia (Kabwe)")


# Create an empty list to store all objects
all_objects <- list()

# Loop over the names of your objects
for (i in 1:12) {
  # Generate the name of the object
  name <- paste("foimat", i, sep = "")
  
  # Get the object by its name and store it in the list
  all_objects[[i]] <- get(name)
}

# Now, all_objects is a list of your objects

foimatSSA <- do.call(rbind, all_objects)
write.csv(foimatSSA, file = "foimatSSA.csv", row.names = FALSE)
```

```{r FOI func}
# second version FoI graph
plotFOIXY <- function(foimatrix){
  g <- ggplot(foimatrix, aes(x = Year, ymin = lo, ymax = hi, y = FOI))+
    geom_ribbon(alpha= 0.2, fill = "#C05746")+
    geom_line(color = "#C05746")+
    theme_bw()+
    theme(axis.text.y = element_text(angle = 45, hjust = 1, size = 8)) +
    ylab(element_blank())+
    scale_y_continuous(limits = c(0.0, 1.0), breaks = seq(0.0, 1.0, by = 0.1))+
    xlab(element_blank())+
    facet_wrap(~ country, nrow = 1) 
  return(g)
}

plotFOIXOnly <- function(foimatrix){
  g <- ggplot(foimatrix, aes(x = Year, ymin = lo, ymax = hi, y = FOI))+
    geom_ribbon(alpha= 0.2, fill = "#C05746")+
    geom_line(color = "#C05746")+
    theme_bw()+
    theme(axis.line.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_blank())+
    ylab(element_blank())+
    scale_y_continuous(limits = c(0.0, 1.0), breaks = seq(0.0, 1.0, by = 0.1))+
    facet_wrap(~ country, nrow = 1) 
  return(g)
}
```

```{r FOI plot, echo = FALSE}
foi1 <- plotFOIXY(foimat1)
foi1

foi2 <- plotFOIXOnly(foimat2)
foi2 

foi3 <- plotFOIXOnly(foimat3)
foi3

foi4 <- plotFOIXY(foimat4)
foi4

foi5 <- plotFOIXOnly(foimat5)
foi5 

foi6 <- plotFOIXOnly(foimat6)
foi6

foi7 <- plotFOIXY(foimat7)
foi7

foi8 <- plotFOIXOnly(foimat8)
foi8 

foi9 <- plotFOIXOnly(foimat9)
foi9

foi10 <- plotFOIXY(foimat10)
foi10

foi11 <- plotFOIXOnly(foimat11)
foi11

foi12 <- plotFOIXOnly(foimat12)
foi12

ssa_foi  <-  grid.arrange(foi1, foi2, foi3, 
                           foi4, foi5, foi6, 
                           foi7, foi8, foi9, 
                           foi10, foi11, foi12, ncol=3)

ggsave("ssa_foi.pdf", ssa_foi, dpi=1000, device= "pdf", height=8, width=12,units="in", bg=NULL)

# for present
ssaSerofoi<-  ggarrange(ssa_sero, ssa_foi, 
          labels = c("A", "B"),
          ncol = 2)

ggsave("ssaSerofoi.pdf", ssaSerofoi, dpi=1000, device= "pdf", height=8, width=12,units="in", bg=NULL)

```

```{r raw serograph}
ssa_igg$ymin <- ssa_igg$lower
ssa_igg$ymax <- ssa_igg$upper

ssaRawSero <- ggplot(ssa_igg) +
  geom_rect(aes(xmin = age_min, xmax = age_max, ymin = ymin, ymax = ymax, 
                fill = as.factor(author)), alpha = 0.5) +
  labs(x = "Age Group", y = "Seropositivity (%)", fill = "Study") +
  theme_bw()+
  facet_wrap(~country)+
   theme(strip.text = element_text(size = 7))

ggsave("ssaRawSero.pdf", ssaRawSero, dpi=100, device= "pdf", height=8, width=12,units="in", bg=NULL)
```

```{r save}
save(outDf7, outDf204_1, outDf279, outDf279,
     outDf236, outDf149, outDf170, outDf204_2,
     outDf494, outDf237, outDf17, outDf306,
     outDf106, 
     mcmcMatrix1, mcmcMatrix2, mcmcMatrix3,
     mcmcMatrix4, mcmcMatrix4, mcmcMatrix5,
     mcmcMatrix6, mcmcMatrix7, mcmcMatrix8,
     mcmcMatrix9, mcmcMatrix10, mcmcMatrix11,
     mcmcMatrix12, ssa_foi, ssaSerofoi, file = "SSAOutDf.RData")
save(plotfuncXonly,
     plotfuncYonly, plotfuncNone, plotfuncXY, quantmat, file = "plotFunc.RData")

```
